// <auto-generated />
namespace Eitan.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Update120220132 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update120220132));
        
        string IMigrationMetadata.Id
        {
            get { return "201302121139589_Update12022013-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
