// <auto-generated />
namespace Eitan.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Update2342310 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update2342310));
        
        string IMigrationMetadata.Id
        {
            get { return "201302151650032_Update2342310"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
