// <auto-generated />
namespace Eitan.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SEO : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SEO));
        
        string IMigrationMetadata.Id
        {
            get { return "201302161405403_SEO"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
