// <auto-generated />
namespace Eitan.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class check2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(check2));
        
        string IMigrationMetadata.Id
        {
            get { return "201302021257502_check2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
