// <auto-generated />
namespace Eitan.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SEO2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SEO2));
        
        string IMigrationMetadata.Id
        {
            get { return "201302161417235_SEO2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
